#********************************************************************************PATH********************************************************************************
# Output
output_dir: '../store/001/eval'

# Data
test_path: '../data/test.csv'

# Checkpoint
eval_checkpoint: '../store/train_1/checkpoint_01.pth'

#********************************************************************************EVAL********************************************************************************
# Device
device: 'cuda:0'

# Param
batch_size: 32
max_epoch: 500
early_stop: 5

# Optimizer
eta: 0.0001
weight_decay: 0.001

#********************************************************************************MODEL********************************************************************************
# Loss
loss:
  - loss_heatmap
  - loss_link
  - loss_keypoint

# OpenPose (Exogenous) Dimensions
channel: 21
height: 20
width: 20
depth: 18

# Window Size
window_size: 10